/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { NadiPassRegistry } from "./NadiPassRegistry";
export * as factories from "./factories";
export { NadiPassRegistry__factory } from "./factories/NadiPassRegistry__factory";
