/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NadiPassRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "breakGlassCount"
      | "getBreakGlassCount"
      | "getPatientOwner"
      | "getPatientProfile"
      | "logBreakGlass"
      | "patientOwners"
      | "patientProfiles"
      | "registerIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BreakGlassLogged" | "IdentityRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "breakGlassCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBreakGlassCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientOwner",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPatientProfile",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logBreakGlass",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "patientOwners",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "patientProfiles",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "breakGlassCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBreakGlassCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPatientProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logBreakGlass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientOwners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientProfiles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
}

export namespace BreakGlassLoggedEvent {
  export type InputTuple = [
    patientIdHash: BytesLike,
    eventHash: BytesLike,
    reasonCode: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientIdHash: string,
    eventHash: string,
    reasonCode: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientIdHash: string;
    eventHash: string;
    reasonCode: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    patientIdHash: BytesLike,
    profileHash: BytesLike,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    patientIdHash: string,
    profileHash: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    patientIdHash: string;
    profileHash: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NadiPassRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NadiPassRegistry;
  waitForDeployment(): Promise<this>;

  interface: NadiPassRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  breakGlassCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getBreakGlassCount: TypedContractMethod<
    [patientIdHash: BytesLike],
    [bigint],
    "view"
  >;

  getPatientOwner: TypedContractMethod<
    [patientIdHash: BytesLike],
    [string],
    "view"
  >;

  getPatientProfile: TypedContractMethod<
    [patientIdHash: BytesLike],
    [string],
    "view"
  >;

  logBreakGlass: TypedContractMethod<
    [patientIdHash: BytesLike, eventHash: BytesLike, reasonCode: BigNumberish],
    [void],
    "nonpayable"
  >;

  patientOwners: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  patientProfiles: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  registerIdentity: TypedContractMethod<
    [patientIdHash: BytesLike, profileHash: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "breakGlassCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBreakGlassCount"
  ): TypedContractMethod<[patientIdHash: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPatientOwner"
  ): TypedContractMethod<[patientIdHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPatientProfile"
  ): TypedContractMethod<[patientIdHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "logBreakGlass"
  ): TypedContractMethod<
    [patientIdHash: BytesLike, eventHash: BytesLike, reasonCode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "patientOwners"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "patientProfiles"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [patientIdHash: BytesLike, profileHash: BytesLike, owner: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BreakGlassLogged"
  ): TypedContractEvent<
    BreakGlassLoggedEvent.InputTuple,
    BreakGlassLoggedEvent.OutputTuple,
    BreakGlassLoggedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;

  filters: {
    "BreakGlassLogged(bytes32,bytes32,uint8,uint256)": TypedContractEvent<
      BreakGlassLoggedEvent.InputTuple,
      BreakGlassLoggedEvent.OutputTuple,
      BreakGlassLoggedEvent.OutputObject
    >;
    BreakGlassLogged: TypedContractEvent<
      BreakGlassLoggedEvent.InputTuple,
      BreakGlassLoggedEvent.OutputTuple,
      BreakGlassLoggedEvent.OutputObject
    >;

    "IdentityRegistered(bytes32,bytes32,address,uint256)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
  };
}
